name: SQL Linter
on:
  push:
    branches: [ main ]
jobs:
  SQLLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install sqlfluff
        run: pip install sqlfluff
      - name: Lint SQL schema (PostgreSQL dialect)
        run: sqlfluff lint $GITHUB_WORKSPACE/DataSchemaModified.sql --dialect postgres
