name: Print Software Versions
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  DataProcessingSoftware:
    runs-on: ubuntu-latest
    steps:
      - name: Check Node.js version
        run: node --version
      - name: Check Python version
        run: python3 --version
  DatabaseSoftware:
    runs-on: ubuntu-latest
    steps:
      - name: Check PostgreSQL client version
        run: psql --version
